theme = "naysayer"

[editor]
line-number = "relative"
mouse = false
# shell = ["pwsh"]
cursorline = true
color-modes = true
lsp.display-inlay-hints = true

[editor.soft-wrap]
enable = true
max-wrap = 100 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it

[editor.cursor-shape]
insert = "bar"
select = "underline"
normal = "block"

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "total-line-numbers", "position", "file-encoding"]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[keys.normal]
esc = ["collapse_selection"]

[keys.normal.space]
x = ":buffer-close"
