[language-server]
ols = { command = "ols", args = [] }


[[language]]
name = "odin"
auto-format = false
scope = "scope.odin" # "source.odin"
file-types = ["odin"]
roots = ["ols.json"]
language-servers = [ "ols" ]
comment-token = "//"
indent = { tab-width = 1, unit = "\t" }
injection-regex = "odin"
formatter = { command = "odinfmt", args = [ "-stdin", "true" ] }

[[grammar]]
name = "odin"
source = { git = "https://github.com/amaanq/tree-sitter-odin" }
